api_platform:

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: [application/ld+json]
        json: [application/json]
        html: [text/html]
    patch_formats:
        json: ['application/merge-patch+json']
        multipart: ['multipart/form-data']
    swagger:
        versions: [3]
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
